site_name: Documentation du Kalepin
theme:
  name: 'material'
  logo: assets/logo.png
  language: fr
  palette:
    primary: lime

extra:
  homepage: http://lekalepin.fr/
  generator: false  
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/lafabrikmdl

nav:
  - Accueil: index.md

copyright: Association La Fabrik
